/**
 * The words of wine labels (and of beer and cider labels): grapes, styles and quality levels, regions and
 * appellations, and the words that mark the name of a producer ("Weingut", "Domaine", "Winery"), each with its
 * canonical spelling. Matched without accents and case, so OCR's "SPATLESE" is "Spätlese".
 */

export type LexiconKind = 'grape' | 'style' | 'region' | 'prefix' | 'suffix';

export type LexiconEntry = {
  kind: LexiconKind;
  /** the canonical spelling, e.g. Spätlese */
  name: string;
  /** a region whose name is the name of its wines (Mercurey, Pessac-Léognan, Chablis), not only where they come from */
  names?: boolean;
  /** red or white, for a grape */
  color?: 'red' | 'white';
  /** the kind of drink a style word says, e.g. Sparkling for Brut */
  type?: WineType;
};

export type WineType = 'Red' | 'White' | 'Rosé' | 'Sparkling' | 'Sweet' | 'Fortified' | 'Beer' | 'Cider';

const RED_GRAPES = [
  'Pinot Noir',
  'Spätburgunder',
  'Cabernet Sauvignon',
  'Cabernet Franc',
  'Merlot',
  'Syrah',
  'Shiraz',
  'Grenache',
  'Garnacha',
  'Tempranillo',
  'Sangiovese',
  'Nebbiolo',
  'Barbera',
  'Dolcetto',
  'Zinfandel',
  'Primitivo',
  'Malbec',
  'Carménère',
  'Mourvèdre',
  'Monastrell',
  'Petite Sirah',
  'Petit Verdot',
  'Gamay',
  'Pinotage',
  'Touriga Nacional',
  'Tannat',
  'Carignan',
  'Mencía',
  'Aglianico',
  "Nero d'Avola",
  'Montepulciano',
  'Corvina',
  'Lagrein',
  'Dornfelder',
  'Blaufränkisch',
  'Zweigelt',
  'Saint Laurent',
  'Xinomavro',
];

const WHITE_GRAPES = [
  'Riesling',
  'Chardonnay',
  'Sauvignon Blanc',
  'Pinot Grigio',
  'Pinot Gris',
  'Pinot Blanc',
  'Grauburgunder',
  'Weissburgunder',
  'Weißburgunder',
  'Gewürztraminer',
  'Viognier',
  'Roussanne',
  'Marsanne',
  'Chenin Blanc',
  'Sémillon',
  'Muscat',
  'Moscato',
  'Muskateller',
  'Torrontés',
  'Albariño',
  'Alvarinho',
  'Verdejo',
  'Viura',
  'Macabeo',
  'Palomino Fina',
  'Palomino',
  'Pedro Ximénez',
  'Grüner Veltliner',
  'Silvaner',
  'Sylvaner',
  'Müller-Thurgau',
  'Rivaner',
  'Kerner',
  'Scheurebe',
  'Elbling',
  'Vermentino',
  'Trebbiano',
  'Garganega',
  'Glera',
  'Fiano',
  'Greco',
  'Falanghina',
  'Arneis',
  'Cortese',
  'Furmint',
  'Assyrtiko',
  'Godello',
  'Loureiro',
  'Aligoté',
  'Melon de Bourgogne',
  'Colombard',
];

const STYLES: Array<[string, WineType?]> = [
  ['Trockenbeerenauslese', 'Sweet'],
  ['Beerenauslese', 'Sweet'],
  ['Auslese', 'Sweet'],
  ['Spätlese'],
  ['Kabinett'],
  ['Eiswein', 'Sweet'],
  ['Edelsüß', 'Sweet'],
  ['Trocken'],
  ['Halbtrocken'],
  ['Feinherb'],
  ['Brut Nature', 'Sparkling'],
  ['Extra Brut', 'Sparkling'],
  ['Brut', 'Sparkling'],
  ['Demi-Sec', 'Sparkling'],
  ['Crémant', 'Sparkling'],
  ['Sekt', 'Sparkling'],
  ['Cava', 'Sparkling'],
  ['Prosecco', 'Sparkling'],
  ['Spumante', 'Sparkling'],
  ['Franciacorta', 'Sparkling'],
  ['Sparkling', 'Sparkling'],
  ['Blanc de Blancs'],
  ['Blanc de Noirs'],
  ['Blanc de Noir'],
  ['Rosé', 'Rosé'],
  ['Rosado', 'Rosé'],
  ['Rosato', 'Rosé'],
  ['Gran Reserva'],
  ['Reserva'],
  ['Riserva'],
  ['Reserve'],
  ['Réserve'],
  ['Crianza'],
  ['Grand Cru'],
  ['Premier Cru'],
  ['1er Cru'],
  ['Grand Cru Classé'],
  ['Cru Bourgeois'],
  ['Vieilles Vignes'],
  ['Late Harvest', 'Sweet'],
  ['Ice Wine', 'Sweet'],
  ['Icewine', 'Sweet'],
  ['Vendanges Tardives', 'Sweet'],
  ['Fino', 'Fortified'],
  ['Manzanilla', 'Fortified'],
  ['Amontillado', 'Fortified'],
  ['Oloroso', 'Fortified'],
  ['Sherry', 'Fortified'],
  ['Porto', 'Fortified'],
  ['Madeira', 'Fortified'],
  ['Tawny', 'Fortified'],
  ['Barrel Aged'],
  ['Ale', 'Beer'],
  ['Pale Ale', 'Beer'],
  ['IPA', 'Beer'],
  ['Lager', 'Beer'],
  ['Pilsner', 'Beer'],
  ['Stout', 'Beer'],
  ['Saison', 'Beer'],
  ['Weissbier', 'Beer'],
  ['Cider', 'Cider'],
  ['Cidre', 'Cider'],
];

/** regions and appellations; `true` for the ones whose name is the name of the wine */
const REGIONS: Array<[string, boolean?]> = [
  // Germany and Austria
  ['Mosel-Saar-Ruwer'],
  ['Mosel'],
  ['Saar'],
  ['Ruwer'],
  ['Rheinhessen'],
  ['Rheingau'],
  ['Pfalz'],
  ['Nahe'],
  ['Baden'],
  ['Franken'],
  ['Württemberg'],
  ['Ahr'],
  ['Wachau'],
  ['Kamptal'],
  ['Burgenland'],
  // France
  ['Bourgogne', true],
  ['Burgundy'],
  ['Bordeaux', true],
  ['Bordeaux Supérieur', true],
  ['Pessac-Léognan', true],
  ['Graves', true],
  ['Médoc', true],
  ['Haut-Médoc', true],
  ['Saint-Émilion', true],
  ['Pomerol', true],
  ['Margaux', true],
  ['Pauillac', true],
  ['Saint-Julien', true],
  ['Saint-Estèphe', true],
  ['Sauternes', true],
  ['Chablis', true],
  ['Meursault', true],
  ['Puligny-Montrachet', true],
  ['Chassagne-Montrachet', true],
  ['Mercurey', true],
  ['Givry', true],
  ['Rully', true],
  ['Pouilly-Fuissé', true],
  ['Pouilly-Fumé', true],
  ['Mâcon', true],
  ['Mâcon-Villages', true],
  ['Beaujolais', true],
  ['Beaujolais-Villages', true],
  ['Morgon', true],
  ['Fleurie', true],
  ['Nuits-Saint-Georges', true],
  ['Gevrey-Chambertin', true],
  ['Volnay', true],
  ['Pommard', true],
  ['Beaune', true],
  ['Côte de Beaune', true],
  ['Côte de Nuits', true],
  ['Côtes du Rhône', true],
  ['Châteauneuf-du-Pape', true],
  ['Gigondas', true],
  ['Crozes-Hermitage', true],
  ['Hermitage', true],
  ['Côte-Rôtie', true],
  ['Sancerre', true],
  ['Vouvray', true],
  ['Chinon', true],
  ['Muscadet', true],
  ['Loire'],
  ['Alsace'],
  ['Champagne', true],
  ['Languedoc'],
  ['Provence'],
  ['Côtes de Provence', true],
  ['Bandol', true],
  ['Cahors', true],
  // Spain and Portugal
  ['Rioja', true],
  ['Ribera del Duero', true],
  ['Priorat', true],
  ['Cariñena'],
  ['Jerez'],
  ['Rías Baixas', true],
  ['Rueda', true],
  ['Toro', true],
  ['Penedès'],
  ['Cádiz'],
  ['Vino de la Tierra de Cádiz'],
  ['Douro', true],
  ['Dão', true],
  ['Vinho Verde', true],
  ['Alentejo'],
  // Italy
  ['Toscana'],
  ['Tuscany'],
  ['Chianti', true],
  ['Chianti Classico', true],
  ['Brunello di Montalcino', true],
  ['Montalcino'],
  ['Barolo', true],
  ['Barbaresco', true],
  ['Piemonte'],
  ['Valpolicella', true],
  ['Amarone della Valpolicella', true],
  ['Soave', true],
  ['Veneto'],
  ['Sicilia'],
  ['Etna', true],
  ['Alto Adige'],
  // the Americas
  ['Napa Valley'],
  ['Sonoma County'],
  ['Sonoma Coast'],
  ['Russian River Valley'],
  ['Alexander Valley'],
  ['Carneros'],
  ['Paso Robles'],
  ['Santa Barbara County'],
  ['Santa Rita Hills'],
  ['Central Coast'],
  ['Lodi'],
  ['California'],
  ['Willamette Valley'],
  ['Oregon'],
  ['Columbia Valley'],
  ['Walla Walla Valley'],
  ['Horse Heaven Hills'],
  ['Yakima Valley'],
  ['Red Mountain'],
  ['Washington'],
  ['Finger Lakes'],
  ['Mendoza'],
  ['Salta'],
  ['Maipo Valley'],
  ['Colchagua Valley'],
  ['Casablanca Valley'],
  // elsewhere
  ['Barossa Valley'],
  ['McLaren Vale'],
  ['Hunter Valley'],
  ['Yarra Valley'],
  ['Margaret River'],
  ['Clare Valley'],
  ['Eden Valley'],
  ['Coonawarra'],
  ['Tasmania'],
  ['Derwent Valley'],
  ['Marlborough'],
  ['Central Otago'],
  ['Hawke’s Bay'],
  ['Stellenbosch'],
  ['Swartland'],
  ['Tokaj'],
];

/** words before the name of a producer, e.g. Weingut Willi Haag */
const PREFIXES = [
  'Weingut',
  'Weinbau',
  'Weinhaus',
  'Sektkellerei',
  'Domaine',
  'Château',
  'Chateau',
  'Clos',
  'Maison',
  'Bodega',
  'Bodegas',
  'Castillo',
  'Cantina',
  'Cantine',
  'Tenuta',
  'Castello',
  'Fattoria',
  'Quinta',
  'Herdade',
];

/** words after the name of a producer, e.g. Cairdeas Winery */
const SUFFIXES = [
  'Winery',
  'Wines',
  'Vineyard',
  'Vineyards',
  'Vineyards and Winery',
  'Cellars',
  'Estate',
  'Estates',
  'Wine Estate',
  'Vintners',
  'Wine Company',
  'Brewing',
  'Brewing Co',
  'Brewing Company',
  'Brewing Project',
  'Brewery',
  'Cidery',
];

export const WINE_LEXICON: LexiconEntry[] = [
  ...RED_GRAPES.map((name): LexiconEntry => ({ kind: 'grape', name, color: 'red' })),
  ...WHITE_GRAPES.map((name): LexiconEntry => ({ kind: 'grape', name, color: 'white' })),
  ...STYLES.map(([name, type]): LexiconEntry => ({ kind: 'style', name, ...(type && { type }) })),
  ...REGIONS.map(([name, names]): LexiconEntry => ({ kind: 'region', name, ...(names && { names }) })),
  ...PREFIXES.map((name): LexiconEntry => ({ kind: 'prefix', name })),
  ...SUFFIXES.map((name): LexiconEntry => ({ kind: 'suffix', name })),
];

/** "Spätlese" → "spatlese", "Mosel-Saar-Ruwer" → "mosel saar ruwer" */
export const normalizeWords = (text: string) =>
  text
    .normalize('NFD')
    .replaceAll(/\p{Diacritic}/gu, '')
    .replaceAll('ß', 'ss')
    .toLowerCase()
    .replaceAll(/[^\p{L}\d]+/gu, ' ')
    .trim();

/** the lexicon by normalized words, longest first, so that "Pinot Noir" is found before "Noir" and "Mosel-Saar-Ruwer" before "Mosel" */
export const LEXICON_WORDS = WINE_LEXICON.map((entry) => ({ ...entry, words: normalizeWords(entry.name).split(' ') }))
  .filter((entry, index, all) => all.findIndex((other) => other.words.join(' ') === entry.words.join(' ')) === index)
  .toSorted((a, b) => b.words.join(' ').length - a.words.join(' ').length);

/** common words of labels that never tell two wines apart */
export const COMMON_WORDS = new Set(
  [
    'wine',
    'wines',
    'vin',
    'vino',
    'vinho',
    'wein',
    'weine',
    'red',
    'white',
    'rose',
    'dry',
    'sweet',
    'the',
    'and',
    'des',
    'del',
    'della',
    'von',
    'und',
    'with',
    'from',
    'grand',
    'vieux',
    'cuvee',
    'selection',
    'family',
    'estate',
    'grown',
    'bottled',
    'produced',
    'product',
    'produce',
    'germany',
    'france',
    'italy',
    'spain',
    'portugal',
    'argentina',
    'australia',
    'usa',
    'appellation',
    'controlee',
    'contralte',
    'proprietaires',
    'proprietaire',
    'recoltant',
    'qualitatswein',
    'pradikatswein',
    'deutscher',
    'gutsabfullung',
    'erzeugerabfullung',
    'finest',
    'since',
    'crisp',
    'refreshing',
    'traditional',
    'methods',
    'collection',
    'limited',
    'release',
    'reserve',
    'vineyard',
    'vineyards',
    'winery',
    'weingut',
    'domaine',
    'chateau',
    'bodega',
    'bodegas',
  ].map((word) => word),
);
