-- NOTE: This file is auto generated by ./sql-generator

-- ActivityLogRepository.create
insert into
  "activity_log" (
    "userId",
    "source",
    "action",
    "summary",
    "groupId"
  )
values
  ($1, $2, $3, $4, $5)
returning
  *

-- ActivityLogRepository.getByIds
select
  *
from
  "activity_log"
where
  "activity_log"."userId" = $1
  and "activity_log"."id" = any ($2::uuid[])
order by
  "activity_log"."createdAt" desc

-- ActivityLogRepository.search
select
  *
from
  "activity_log"
where
  "activity_log"."userId" = $1
  and "activity_log"."undoneAt" is null
order by
  "activity_log"."createdAt" desc,
  "activity_log"."id" desc
limit
  $2
offset
  $3

-- ActivityLogRepository.setUndone
update "activity_log"
set
  "undoneAt" = clock_timestamp(),
  "undoneBy" = $1
where
  "activity_log"."id" = any ($2::uuid[])
  and "activity_log"."undoneAt" is null
returning
  "activity_log"."id"

-- ActivityLogRepository.clearUndone
update "activity_log"
set
  "undoneAt" = $1,
  "undoneBy" = $2
where
  "activity_log"."id" = $3

-- ActivityLogRepository.deleteOlderThan
delete from "activity_log"
where
  "activity_log"."createdAt" < $1
delete from "book_revision"
where
  "book_revision"."createdAt" < $1

-- ActivityLogRepository.countGroup
select
  count(*) as "count"
from
  "activity_log"
where
  "activity_log"."groupId" = $1
  and "activity_log"."undoneAt" is null

-- ActivityLogRepository.createRevision
insert into
  "book_revision" ("bookId", "snapshot")
values
  ($1, $2)
returning
  "book_revision"."id",
  "book_revision"."createdAt"

-- ActivityLogRepository.getRevision
select
  *
from
  "book_revision"
where
  "book_revision"."id" = $1

-- ActivityLogRepository.pruneRevisions
delete from "book_revision"
where
  "book_revision"."bookId" = $1
  and "book_revision"."id" not in (
    select
      "book_revision"."id"
    from
      "book_revision"
    where
      "book_revision"."bookId" = $2
    order by
      "book_revision"."createdAt" desc
    limit
      $3
  )

-- ActivityLogRepository.getBookPlacements
select
  "book_page_asset"."assetId",
  "book"."id" as "bookId",
  "book"."title",
  "book_page"."position" as "position"
from
  "book_page_asset"
  inner join "book_page" on "book_page"."id" = "book_page_asset"."pageId"
  inner join "book" on "book"."id" = "book_page"."bookId"
where
  "book_page_asset"."assetId" = any ($1::uuid[])
union all
select
  "book"."coverAssetId" as "assetId",
  "book"."id" as "bookId",
  "book"."title",
  null::integer as "position"
from
  "book"
where
  "book"."coverAssetId" = any ($2::uuid[])

-- ActivityLogRepository.getAlbumsOfAssets
select
  "album_asset"."assetId",
  "album"."id" as "albumId",
  "album"."albumName"
from
  "album_asset"
  inner join "album" on "album"."id" = "album_asset"."albumId"
where
  "album_asset"."assetId" = any ($1::uuid[])
  and "album"."deletedAt" is null

-- ActivityLogRepository.getAssets
select
  "asset"."id",
  "asset"."ownerId",
  "asset"."stackId",
  "asset"."deletedAt",
  "asset"."status",
  "asset"."originalFileName",
  "asset_exif"."description"
from
  "asset"
  left join "asset_exif" on "asset_exif"."assetId" = "asset"."id"
where
  "asset"."id" = any ($1::uuid[])

-- ActivityLogRepository.getStack
select
  "stack"."id",
  "stack"."primaryAssetId",
  (
    select
      coalesce(array_agg("asset"."id"), '{}') as "ids"
    from
      "asset"
    where
      "asset"."stackId" = "stack"."id"
  ) as "assetIds"
from
  "stack"
where
  "stack"."id" = $1

-- ActivityLogRepository.getAlbumState
select
  "album"."id",
  "album"."albumName",
  "album"."description",
  "album"."deletedAt",
  (
    select
      coalesce(array_agg("album_asset"."assetId"), '{}') as "ids"
    from
      "album_asset"
    where
      "album_asset"."albumId" = "album"."id"
  ) as "assetIds",
  (
    select
      count(*) as "count"
    from
      "album_user"
    where
      "album_user"."albumId" = "album"."id"
      and "album_user"."role" != $1
  ) as "sharedUsers",
  (
    select
      count(*) as "count"
    from
      "shared_link"
    where
      "shared_link"."albumId" = "album"."id"
  ) as "sharedLinks"
from
  "album"
where
  "album"."id" = $2

-- ActivityLogRepository.countBookSharedLinks
select
  count(*) as "count"
from
  "shared_link"
where
  "shared_link"."bookId" = $1
