-- NOTE: This file is auto generated by ./sql-generator

-- AgentRepository.createSession
insert into
  "agent_session" ("userId", "profile")
values
  ($1, $2)
returning
  *

-- AgentRepository.getSession
select
  *
from
  "agent_session"
where
  "agent_session"."id" = $1

-- AgentRepository.getSessions
select
  *
from
  "agent_session"
where
  "agent_session"."userId" = $1
order by
  "agent_session"."updatedAt" desc

-- AgentRepository.updateSession
update "agent_session"
set
  "status" = $1
where
  "agent_session"."id" = $2
returning
  *

-- AgentRepository.deleteSession
delete from "agent_session"
where
  "agent_session"."id" = $1

-- AgentRepository.resetRunningSessions
update "agent_session"
set
  "status" = $1
where
  "agent_session"."status" = $2

-- AgentRepository.createMessage
insert into
  "agent_message" ("sessionId", "role", "kind", "content")
values
  ($1, $2, $3, $4)
returning
  *

-- AgentRepository.updateMessage
update "agent_message"
set
  "content" = $1
where
  "agent_message"."id" = $2
returning
  *

-- AgentRepository.getMessages
select
  *
from
  "agent_message"
where
  "agent_message"."sessionId" = $1
order by
  "agent_message"."createdAt" asc,
  "agent_message"."id" asc

-- AgentRepository.getMessageByExternalId
select
  *
from
  "agent_message"
where
  "agent_message"."sessionId" = $1
  and "agent_message"."externalId" = $2
order by
  "agent_message"."createdAt" desc
limit
  $3

-- AgentRepository.getRecentTextMessages
select
  *
from
  "agent_message"
where
  "agent_message"."sessionId" = $1
  and "agent_message"."kind" = $2
order by
  "agent_message"."createdAt" desc
limit
  $3

-- AgentRepository.getAuthUser
select
  "user"."id",
  "user"."name",
  "user"."email",
  "user"."isAdmin",
  "user"."quotaUsageInBytes",
  "user"."quotaSizeInBytes"
from
  "user"
where
  "user"."id" = $1
  and "user"."deletedAt" is null
