-- NOTE: This file is auto generated by ./sql-generator

-- ArtJobRepository.create
insert into
  "art_job" ("userId", "sourceAssetId", "prompt", "profile")
values
  ($1, $2, $3, $4)
returning
  *

-- ArtJobRepository.get
select
  *
from
  "art_job"
where
  "art_job"."id" = $1

-- ArtJobRepository.update
update "art_job"
set
  "status" = $1
where
  "art_job"."id" = $2
returning
  *

-- ArtJobRepository.getDerivedAssetsForTagging
select
  "asset"."id" as "assetId",
  "asset"."ownerId",
  "art_job"."id" as "artJobId",
  "art_job"."style",
  "asset"."originalFileName"
from
  "asset"
  inner join "asset_exif" on "asset_exif"."assetId" = "asset"."id"
  left join "art_job" on "art_job"."resultAssetId" = "asset"."id"
where
  "asset"."deletedAt" is null
  and (
    "art_job"."status" = $1
    or (
      "asset"."originalFileName" like $2
      and "asset_exif"."description" like $3
    )
    or (
      "asset"."originalFileName" like $4
      and "asset_exif"."description" like $5
    )
    or (
      "asset"."originalFileName" like $6
      and "asset_exif"."description" like $7
    )
  )

-- ArtJobRepository.failUnfinished
update "art_job"
set
  "status" = $1,
  "error" = $2
where
  "art_job"."status" in ($3, $4)
