-- NOTE: This file is auto generated by ./sql-generator

-- ArtJobRepository.create
insert into
  "art_job" ("userId", "sourceAssetId", "prompt", "profile")
values
  ($1, $2, $3, $4)
returning
  *

-- ArtJobRepository.get
select
  *
from
  "art_job"
where
  "art_job"."id" = $1

-- ArtJobRepository.update
update "art_job"
set
  "status" = $1
where
  "art_job"."id" = $2
returning
  *

-- ArtJobRepository.failUnfinished
update "art_job"
set
  "status" = $1,
  "error" = $2
where
  "art_job"."status" in ($3, $4)
