-- NOTE: This file is auto generated by ./sql-generator

-- BookRepository.create
insert into
  "book" ("ownerId", "title")
values
  ($1, $2)
returning
  *,
  0 as "pageCount",
  null as "firstPageId"

-- BookRepository.get
select
  "book".*,
  (
    select
      count(*) as "count"
    from
      "book_page"
    where
      "book_page"."bookId" = "book"."id"
  ) as "pageCount",
  (
    select
      "book_page"."id"
    from
      "book_page"
    where
      "book_page"."bookId" = "book"."id"
    order by
      "book_page"."position" asc
    limit
      $1
  ) as "firstPageId"
from
  "book"
where
  "book"."id" = $2

-- BookRepository.getAll
select
  "book".*,
  (
    select
      count(*) as "count"
    from
      "book_page"
    where
      "book_page"."bookId" = "book"."id"
  ) as "pageCount",
  (
    select
      "book_page"."id"
    from
      "book_page"
    where
      "book_page"."bookId" = "book"."id"
    order by
      "book_page"."position" asc
    limit
      $1
  ) as "firstPageId"
from
  "book"
where
  "book"."ownerId" = $2
order by
  "book"."updatedAt" desc

-- BookRepository.update
update "book"
set
  "title" = $1,
  "contentUpdatedAt" = clock_timestamp()
where
  "book"."id" = $2

-- BookRepository.delete
delete from "book"
where
  "book"."id" = $1

-- BookRepository.setExportStatus
update "book"
set
  "exportStatus" = $1
where
  "book"."id" = $2

-- BookRepository.setHtmlExportStatus
update "book"
set
  "htmlExportStatus" = $1
where
  "book"."id" = $2

-- BookRepository.getPages
select
  "book_page".*,
  (
    select
      coalesce(json_agg(agg), '[]')
    from
      (
        select
          "book_page_asset"."slot",
          "book_page_asset"."assetId",
          "book_page_asset"."crop",
          "book_page_asset"."caption"
        from
          "book_page_asset"
        where
          "book_page_asset"."pageId" = "book_page"."id"
        order by
          "book_page_asset"."slot" asc
      ) as agg
  ) as "assets"
from
  "book_page"
where
  "book_page"."bookId" = $1
order by
  "book_page"."position" asc

-- BookRepository.getPage
select
  "book_page".*,
  (
    select
      coalesce(json_agg(agg), '[]')
    from
      (
        select
          "book_page_asset"."slot",
          "book_page_asset"."assetId",
          "book_page_asset"."crop",
          "book_page_asset"."caption"
        from
          "book_page_asset"
        where
          "book_page_asset"."pageId" = "book_page"."id"
        order by
          "book_page_asset"."slot" asc
      ) as agg
  ) as "assets"
from
  "book_page"
where
  "book_page"."bookId" = $1
  and "book_page"."id" = $2

-- BookRepository.addPage
begin
update "book"
set
  "updatedAt" = clock_timestamp(),
  "contentUpdatedAt" = clock_timestamp()
where
  "book"."id" = $1
select
  count(*) as "count"
from
  "book_page"
where
  "book_page"."bookId" = $1
update "book_page"
set
  "position" = "position" + $1
where
  "book_page"."bookId" = $2
  and "book_page"."position" >= $3
insert into
  "book_page" ("layout", "bookId", "position")
values
  ($1, $2, $3)
returning
  "id"
rollback

-- BookRepository.updatePage
begin
update "book"
set
  "updatedAt" = clock_timestamp(),
  "contentUpdatedAt" = clock_timestamp()
where
  "book"."id" = $1
update "book_page"
set
  "layout" = $1
where
  "book_page"."id" = $2
  and "book_page"."bookId" = $3
delete from "book_page_asset"
where
  "book_page_asset"."pageId" = $1
  and "book_page_asset"."slot" >= $2
select
  "book_page".*,
  (
    select
      coalesce(json_agg(agg), '[]')
    from
      (
        select
          "book_page_asset"."slot",
          "book_page_asset"."assetId",
          "book_page_asset"."crop",
          "book_page_asset"."caption"
        from
          "book_page_asset"
        where
          "book_page_asset"."pageId" = "book_page"."id"
        order by
          "book_page_asset"."slot" asc
      ) as agg
  ) as "assets"
from
  "book_page"
where
  "book_page"."id" = $1
  and "book_page"."bookId" = $2
commit

-- BookRepository.removePage
begin
update "book"
set
  "updatedAt" = clock_timestamp(),
  "contentUpdatedAt" = clock_timestamp()
where
  "book"."id" = $1
delete from "book_page"
where
  "book_page"."id" = $1
  and "book_page"."bookId" = $2
update "book_page"
set
  "position" = "ordered"."newPosition"
from
  (
    select
      "id",
      (
        row_number() over (
          order by
            "position",
            "createdAt"
        ) - 1
      )::integer as "newPosition"
    from
      "book_page"
    where
      "bookId" = $1
  ) as "ordered"
where
  "book_page"."id" = "ordered"."id"
  and "book_page"."position" != "ordered"."newPosition"
commit

-- BookRepository.movePage
begin
update "book"
set
  "updatedAt" = clock_timestamp(),
  "contentUpdatedAt" = clock_timestamp()
where
  "book"."id" = $1
select
  "book_page"."id",
  "book_page"."position"
from
  "book_page"
where
  "book_page"."bookId" = $1
order by
  "book_page"."position" asc,
  "book_page"."createdAt" asc
commit

-- BookRepository.replacePages
begin
update "book"
set
  "updatedAt" = clock_timestamp(),
  "contentUpdatedAt" = clock_timestamp()
where
  "book"."id" = $1
delete from "book_page"
where
  "book_page"."bookId" = $1
insert into
  "book_page" ("layout", "bookId", "position")
values
  ($1, $2, $3)
returning
  "book_page"."id",
  "book_page"."position"
rollback

-- BookRepository.upsertSlot
begin
update "book"
set
  "updatedAt" = clock_timestamp(),
  "contentUpdatedAt" = clock_timestamp()
where
  "book"."id" = $1
insert into
  "book_page_asset" ("pageId", "slot", "assetId")
values
  ($1, $2, $3)
on conflict ("pageId", "slot") do update
set
  "assetId" = "excluded"."assetId",
  "crop" = "excluded"."crop",
  "caption" = "excluded"."caption"
rollback

-- BookRepository.updateSlot
begin
update "book"
set
  "updatedAt" = clock_timestamp(),
  "contentUpdatedAt" = clock_timestamp()
where
  "book"."id" = $1
update "book_page_asset"
set
  "caption" = $1
where
  "book_page_asset"."pageId" = $2
  and "book_page_asset"."slot" = $3
commit

-- BookRepository.deleteSlot
begin
update "book"
set
  "updatedAt" = clock_timestamp(),
  "contentUpdatedAt" = clock_timestamp()
where
  "book"."id" = $1
delete from "book_page_asset"
where
  "book_page_asset"."pageId" = $1
  and "book_page_asset"."slot" = $2
commit

-- BookRepository.getAssetsForRender
select
  "asset"."id",
  "asset"."type",
  "asset"."originalPath",
  "asset"."originalFileName",
  "asset"."isEdited",
  "asset"."localDateTime",
  "asset"."width",
  "asset"."height",
  "asset_exif"."exifImageWidth",
  "asset_exif"."exifImageHeight",
  "asset_exif"."orientation",
  (
    select
      coalesce(json_agg(agg), '[]')
    from
      (
        select
          "asset_file"."type",
          "asset_file"."path",
          "asset_file"."isEdited"
        from
          "asset_file"
        where
          "asset_file"."assetId" = "asset"."id"
      ) as agg
  ) as "files"
from
  "asset"
  left join "asset_exif" on "asset_exif"."assetId" = "asset"."id"
where
  "asset"."id" in ($1)
  and "asset"."deletedAt" is null

-- BookRepository.getAssetLocations
select
  "asset"."id",
  "asset"."localDateTime",
  "asset_exif"."latitude",
  "asset_exif"."longitude",
  "asset_exif"."city",
  "asset_exif"."country"
from
  "asset"
  inner join "asset_exif" on "asset_exif"."assetId" = "asset"."id"
where
  "asset"."id" in ($1)
  and "asset"."deletedAt" is null
  and "asset_exif"."latitude" is not null
  and "asset_exif"."longitude" is not null
order by
  "asset"."localDateTime" asc,
  "asset"."id" asc

-- BookRepository.getCountryOutlines
select
  "naturalearth_countries"."admin",
  "coordinates"::text as "coordinates"
from
  "naturalearth_countries"
where
  "coordinates" && polygon(box(point($1, $2), point($3, $4)))
limit
  $5

-- BookRepository.getFaces
select
  "asset_face"."assetId",
  "asset_face"."imageWidth",
  "asset_face"."imageHeight",
  "asset_face"."boundingBoxX1",
  "asset_face"."boundingBoxY1",
  "asset_face"."boundingBoxX2",
  "asset_face"."boundingBoxY2"
from
  "asset_face"
where
  "asset_face"."assetId" in ($1)
  and "asset_face"."deletedAt" is null
  and "asset_face"."isVisible" is true
