-- NOTE: This file is auto generated by ./sql-generator

-- BookDraftRepository.getKeys
select
  "book_draft"."key"
from
  "book_draft"
where
  "book_draft"."ownerId" = $1

-- BookDraftRepository.getPending
select
  "book_draft".*
from
  "book_draft"
  inner join "book" on "book"."id" = "book_draft"."bookId"
where
  "book_draft"."ownerId" = $1
  and "book_draft"."state" = $2
order by
  "book_draft"."createdAt" desc

-- BookDraftRepository.getByBookId
select
  *
from
  "book_draft"
where
  "book_draft"."bookId" = $1

-- BookDraftRepository.claim
insert into
  "book_draft" ("ownerId", "key", "kind", "title", "reason")
values
  ($1, $2, $3, $4, $5)
on conflict ("ownerId", "key") do nothing
returning
  *

-- BookDraftRepository.update
update "book_draft"
set
  "state" = $1
where
  "book_draft"."id" = $2

-- BookDraftRepository.delete
delete from "book_draft"
where
  "book_draft"."id" = $1

-- BookDraftRepository.getCollectionTags
select
  "asset"."id",
  "asset"."localDateTime",
  "tag"."value"
from
  "tag_asset"
  inner join "tag" on "tag"."id" = "tag_asset"."tagId"
  inner join "asset" on "asset"."id" = "tag_asset"."assetId"
where
  "tag"."userId" = $1
  and "asset"."ownerId" = $2
  and "tag"."value" like $3
  and "asset"."visibility" = 'timeline'
  and "asset"."deletedAt" is null
order by
  "asset"."localDateTime" asc

-- BookDraftRepository.getTimeline
select
  "asset"."id",
  "asset"."localDateTime",
  "asset_exif"."latitude",
  "asset_exif"."longitude",
  "asset_exif"."city",
  "asset_exif"."state",
  "asset_exif"."country"
from
  "asset"
  left join "asset_exif" on "asset_exif"."assetId" = "asset"."id"
where
  "asset"."ownerId" = $1
  and "asset"."type" = 'IMAGE'
  and "asset"."visibility" = 'timeline'
  and "asset"."deletedAt" is null
order by
  "asset"."localDateTime" asc

-- BookDraftRepository.getPeopleWithBirthdays
select
  "person"."personGroupId" as "id",
  "person"."name",
  to_char("person"."birthDate", 'YYYY-MM-DD') as "birthDate"
from
  "person"
where
  "person"."ownerId" = $1
  and "person"."isHidden" = $2
  and "person"."name" != $3
  and "person"."birthDate" is not null
order by
  "person"."name"

-- BookDraftRepository.getPersonPhotos
select
  "asset"."id",
  "asset"."localDateTime"
from
  "asset"
where
  exists (
    select
    from
      "asset_face"
    where
      "asset_face"."assetId" = "asset"."id"
      and "asset_face"."personGroupId" = $1::uuid
      and "asset_face"."deletedAt" is null
      and "asset_face"."isVisible" is true
  )
  and "asset"."ownerId" = $2
  and "asset"."type" = 'IMAGE'
  and "asset"."visibility" = 'timeline'
  and "asset"."deletedAt" is null
  and "asset"."localDateTime" >= $3
  and "asset"."localDateTime" < $4
order by
  "asset"."localDateTime" asc
