-- NOTE: This file is auto generated by ./sql-generator

-- CollectionNoticeRepository.getNotices
select
  "collection_notice"."pack",
  "collection_notice"."key",
  "collection_notice"."assetIds"
from
  "collection_notice"
where
  "collection_notice"."userId" = $1

-- CollectionNoticeRepository.claim
insert into
  "collection_notice" ("userId", "pack", "key", "assetIds")
values
  ($1, $2, $3, $4)
on conflict ("userId", "pack", "key") do nothing
returning
  "collection_notice"."id"

-- CollectionNoticeRepository.setNotification
update "collection_notice"
set
  "notificationId" = $1
where
  "collection_notice"."id" = $2

-- CollectionNoticeRepository.delete
delete from "collection_notice"
where
  "collection_notice"."id" = $1

-- CollectionNoticeRepository.getCheckedAt
select
  "collection_notice_check"."checkedAt"
from
  "collection_notice_check"
where
  "collection_notice_check"."userId" = $1

-- CollectionNoticeRepository.setCheckedAt
insert into
  "collection_notice_check" ("userId", "checkedAt")
values
  ($1, $2)
on conflict ("userId") do update
set
  "checkedAt" = $3

-- CollectionNoticeRepository.getUploads
select
  "asset"."id",
  "asset"."localDateTime",
  "asset"."fileCreatedAt",
  "asset"."createdAt"
from
  "asset"
where
  "asset"."ownerId" = $1
  and "asset"."type" = $2
  and "asset"."visibility" in ($3, $4)
  and "asset"."deletedAt" is null
  and "asset"."createdAt" >= $5
order by
  "asset"."createdAt" desc
limit
  $6
