-- NOTE: This file is auto generated by ./sql-generator

-- CollectionNoticeRepository.getNotices
select
  "collection_notice"."pack",
  "collection_notice"."key",
  "collection_notice"."assetIds"
from
  "collection_notice"
where
  "collection_notice"."userId" = $1

-- CollectionNoticeRepository.claim
insert into
  "collection_notice" ("userId", "pack", "key", "assetIds")
values
  ($1, $2, $3, $4)
on conflict ("userId", "pack", "key") do nothing
returning
  "collection_notice"."id"

-- CollectionNoticeRepository.getUnreadSince
select
  "collection_notice"."pack",
  "collection_notice"."assetIds",
  "collection_notice"."createdAt",
  "notification"."title",
  "notification"."description"
from
  "collection_notice"
  inner join "notification" on "notification"."id" = "collection_notice"."notificationId"
where
  "collection_notice"."userId" = $1
  and "collection_notice"."createdAt" >= $2
  and "notification"."readAt" is null
  and "notification"."deletedAt" is null
order by
  "collection_notice"."createdAt" desc

-- CollectionNoticeRepository.setNotification
update "collection_notice"
set
  "notificationId" = $1
where
  "collection_notice"."id" = $2

-- CollectionNoticeRepository.delete
delete from "collection_notice"
where
  "collection_notice"."id" = $1

-- CollectionNoticeRepository.getCheckedAt
select
  "collection_notice_check"."checkedAt"
from
  "collection_notice_check"
where
  "collection_notice_check"."userId" = $1

-- CollectionNoticeRepository.setCheckedAt
insert into
  "collection_notice_check" ("userId", "checkedAt")
values
  ($1, $2)
on conflict ("userId") do update
set
  "checkedAt" = $3

-- CollectionNoticeRepository.getHome
select
  round(asset_exif.latitude::numeric, 1)::float8 as "latitude",
  round(asset_exif.longitude::numeric, 1)::float8 as "longitude",
  count(distinct asset."localDateTime"::date)::int as "days"
from
  "asset"
  inner join "asset_exif" on "asset_exif"."assetId" = "asset"."id"
where
  "asset"."ownerId" = $1
  and "asset"."deletedAt" is null
  and "asset_exif"."latitude" is not null
  and "asset_exif"."longitude" is not null
group by
  1,
  2
order by
  "days" desc
limit
  $2

-- CollectionNoticeRepository.getUploads
select
  "asset"."id",
  "asset"."localDateTime",
  "asset"."fileCreatedAt",
  "asset"."createdAt"
from
  "asset"
where
  "asset"."ownerId" = $1
  and "asset"."type" = $2
  and "asset"."visibility" in ($3, $4)
  and "asset"."deletedAt" is null
  and "asset"."createdAt" >= $5
order by
  "asset"."createdAt" desc
limit
  $6
