-- NOTE: This file is auto generated by ./sql-generator

-- HighlightJobRepository.create
insert into
  "highlight_job" ("ownerId", "title", "options")
values
  ($1, $2, $3)
returning
  *

-- HighlightJobRepository.get
select
  *
from
  "highlight_job"
where
  "highlight_job"."id" = $1

-- HighlightJobRepository.getStatus
select
  "highlight_job"."status"
from
  "highlight_job"
where
  "highlight_job"."id" = $1

-- HighlightJobRepository.update
update "highlight_job"
set
  "status" = $1
where
  "highlight_job"."id" = $2
returning
  *

-- HighlightJobRepository.cancel
update "highlight_job"
set
  "status" = $1
where
  "highlight_job"."id" = $2
  and "highlight_job"."status" in ($3, $4)
returning
  *

-- HighlightJobRepository.getAll
select
  *
from
  "highlight_job"
where
  "highlight_job"."ownerId" = $1
order by
  "highlight_job"."createdAt" desc
limit
  $2

-- HighlightJobRepository.failRunning
update "highlight_job"
set
  "status" = $1,
  "error" = $2
where
  "highlight_job"."status" = $3

-- HighlightJobRepository.getVideos
select
  "asset"."id",
  "asset"."originalPath",
  "asset"."duration",
  "asset"."localDateTime",
  "asset"."isFavorite",
  "asset"."width",
  "asset"."height",
  "asset"."stackId",
  "asset_exif"."latitude",
  "asset_exif"."longitude",
  "asset_exif"."city",
  "asset_exif"."country",
  "asset_exif"."rating",
  "asset_exif"."description"
from
  "asset"
  left join "asset_exif" on "asset_exif"."assetId" = "asset"."id"
where
  "asset"."id" in ($1)
  and "asset"."type" = $2
  and "asset"."visibility" != $3
  and "asset"."deletedAt" is null
order by
  "asset"."localDateTime" asc

-- HighlightJobRepository.getMusic
select
  "asset"."id",
  "asset"."originalFileName",
  "asset"."originalPath",
  "asset"."duration",
  "asset"."createdAt"
from
  "asset"
where
  "asset"."ownerId" = $1
  and "asset"."type" = $2
  and "asset"."deletedAt" is null
order by
  "asset"."createdAt" desc
limit
  $3

-- HighlightJobRepository.getMusicAsset
select
  "asset"."id",
  "asset"."originalFileName",
  "asset"."originalPath",
  "asset"."duration"
from
  "asset"
where
  "asset"."id" = $1
  and "asset"."ownerId" = $2
  and "asset"."type" = $3
  and "asset"."deletedAt" is null
