-- NOTE: This file is auto generated by ./sql-generator

-- MemoryNoticeRepository.claim
insert into
  "memory_notice" ("userId", "kind", "refId", "day")
values
  ($1, $2, $3, $4)
on conflict do nothing
returning
  "memory_notice"."id"

-- MemoryNoticeRepository.setNotification
update "memory_notice"
set
  "notificationId" = $1
where
  "memory_notice"."id" = $2

-- MemoryNoticeRepository.delete
delete from "memory_notice"
where
  "memory_notice"."id" = $1

-- MemoryNoticeRepository.hasDay
select
  "memory_notice"."id"
from
  "memory_notice"
where
  "memory_notice"."userId" = $1
  and "memory_notice"."day" = $2
  and "memory_notice"."kind" in ($3, $4)

-- MemoryNoticeRepository.getSent
select
  "memory_notice"."refId"
from
  "memory_notice"
where
  "memory_notice"."userId" = $1
  and "memory_notice"."kind" = $2
  and "memory_notice"."refId" in ($3)

-- MemoryNoticeRepository.cleanup
delete from "memory_notice"
where
  "memory_notice"."createdAt" < $1
