-- NOTE: This file is auto generated by ./sql-generator

-- MemoryExclusionRepository.getAll
select
  "memory_exclusion"."id",
  "memory_exclusion"."type",
  "memory_exclusion"."personGroupId",
  "memory_exclusion"."albumId",
  "memory_exclusion"."createdAt",
  "person"."name" as "personName",
  "person"."type" as "personType",
  "album"."albumName",
  to_char("memory_exclusion"."startDate", 'YYYY-MM-DD') as "startDate",
  to_char("memory_exclusion"."endDate", 'YYYY-MM-DD') as "endDate"
from
  "memory_exclusion"
  left join "person" on "person"."personGroupId" = "memory_exclusion"."personGroupId"
  and "person"."ownerId" = "memory_exclusion"."ownerId"
  left join "album" on "album"."id" = "memory_exclusion"."albumId"
where
  "memory_exclusion"."ownerId" = $1
order by
  "memory_exclusion"."createdAt" asc,
  "memory_exclusion"."id" asc

-- MemoryExclusionRepository.create
insert into
  "memory_exclusion" ("ownerId", "type", "personGroupId")
values
  ($1, $2, $3)
on conflict do nothing
returning
  "memory_exclusion"."id"

-- MemoryExclusionRepository.delete
delete from "memory_exclusion"
where
  "memory_exclusion"."ownerId" = $1
  and "memory_exclusion"."id" in ($2)
returning
  "memory_exclusion"."id",
  "memory_exclusion"."type",
  "memory_exclusion"."personGroupId",
  "memory_exclusion"."albumId",
  to_char("memory_exclusion"."startDate", 'YYYY-MM-DD') as "startDate",
  to_char("memory_exclusion"."endDate", 'YYYY-MM-DD') as "endDate"

-- MemoryExclusionRepository.findPeopleByName
select
  "person"."personGroupId" as "id",
  "person"."name",
  "person"."type"
from
  "person"
where
  "person"."ownerId" = $1
  and lower(btrim("person"."name")) in ($2)
order by
  "person"."name"

-- MemoryExclusionRepository.getKeptAssetIds
select
  "asset"."id"
from
  "asset"
where
  "asset"."id" in ($1)
  and (
    not exists (
      select
        1 as "one"
      from
        "asset_face"
      where
        "asset_face"."assetId" = "asset"."id"
        and "asset_face"."deletedAt" is null
        and (
          "asset_face"."personGroupId" = any ($2::uuid[])
          or exists (
            select
              1 as "one"
            from
              "face_identity_face"
              inner join "person" on "person"."identityId" = "face_identity_face"."identityId"
            where
              "face_identity_face"."assetFaceId" = "asset_face"."id"
              and "person"."personGroupId" = any ($3::uuid[])
          )
        )
    )
    and (
      "asset"."localDateTime" < $4
      or "asset"."localDateTime" >= $5
    )
    and not exists (
      select
        1 as "one"
      from
        "album_asset"
      where
        "album_asset"."assetId" = "asset"."id"
        and "album_asset"."albumId" = any ($6::uuid[])
    )
    and not exists (
      select
        1 as "one"
      from
        "tag_asset"
        inner join "tag" on "tag"."id" = "tag_asset"."tagId"
      where
        "tag_asset"."assetId" = "asset"."id"
        and (
          "tag"."value" ilike $7
          or "tag"."value" ilike $8
          or "tag"."value" ilike $9
          or "tag"."value" like $10
          or "tag"."value" like $11
          or "tag"."value" like $12
          or "tag"."value" like $13
          or "tag"."value" like $14
          or "tag"."value" like $15
          or "tag"."value" like $16
          or "tag"."value" like $17
          or "tag"."value" like $18
          or "tag"."value" like $19
          or "tag"."value" like $20
          or "tag"."value" like $21
        )
    )
  )
