-- NOTE: This file is auto generated by ./sql-generator

-- RoutineRepository.create
insert into
  "assistant_routine" (
    "ownerId",
    "name",
    "instruction",
    "trigger",
    "limits"
  )
values
  ($1, $2, $3, $4, $5)
returning
  *

-- RoutineRepository.get
select
  *
from
  "assistant_routine"
where
  "assistant_routine"."id" = $1

-- RoutineRepository.getByOwner
select
  *
from
  "assistant_routine"
where
  "assistant_routine"."ownerId" = $1
order by
  "assistant_routine"."createdAt" desc

-- RoutineRepository.countByOwner
select
  count(*) as "count"
from
  "assistant_routine"
where
  "assistant_routine"."ownerId" = $1

-- RoutineRepository.update
update "assistant_routine"
set
  "name" = $1
where
  "assistant_routine"."id" = $2
returning
  *

-- RoutineRepository.delete
begin
select
  "assistant_routine_run"."sessionId"
from
  "assistant_routine_run"
where
  "assistant_routine_run"."routineId" = $1
  and "assistant_routine_run"."sessionId" is not null
delete from "assistant_routine"
where
  "assistant_routine"."id" = $1
commit

-- RoutineRepository.getEventRoutines
select
  *
from
  "assistant_routine"
where
  "assistant_routine"."ownerId" = $1
  and "assistant_routine"."enabled" = $2
  and "assistant_routine"."pausedAt" is null
  and "assistant_routine"."trigger" ->> 'type' = $3
  and "assistant_routine"."trigger" ->> 'event' = $4

-- RoutineRepository.getEventOwners
select distinct
  "assistant_routine"."ownerId"
from
  "assistant_routine"
where
  "assistant_routine"."enabled" = $1
  and "assistant_routine"."pausedAt" is null
  and "assistant_routine"."trigger" ->> 'type' = $2
  and "assistant_routine"."trigger" ->> 'event' = $3

-- RoutineRepository.addEvents
insert into
  "assistant_routine_event" ("routineId", "kind", "assetIds")
values
  ($1, $2, $3)

-- RoutineRepository.getSettledRoutineIds
select
  "assistant_routine_event"."routineId"
from
  "assistant_routine_event"
  inner join "assistant_routine" on "assistant_routine"."id" = "assistant_routine_event"."routineId"
where
  "assistant_routine"."enabled" = $1
  and "assistant_routine"."pausedAt" is null
  and "assistant_routine"."trigger" ->> 'type' = $2
group by
  "assistant_routine_event"."routineId"
having
  (
    max("assistant_routine_event"."createdAt") <= $3
    or min("assistant_routine_event"."createdAt") <= $4
  )

-- RoutineRepository.getDueRoutines
select
  *
from
  "assistant_routine"
where
  "assistant_routine"."enabled" = $1
  and "assistant_routine"."pausedAt" is null
  and "assistant_routine"."nextRunAt" <= $2
order by
  "assistant_routine"."nextRunAt"

-- RoutineRepository.claimSchedule
update "assistant_routine"
set
  "nextRunAt" = $1
where
  "assistant_routine"."id" = $2
  and "assistant_routine"."nextRunAt" = $3
returning
  "assistant_routine"."id"

-- RoutineRepository.takeEvents
delete from "assistant_routine_event"
where
  "assistant_routine_event"."routineId" = $1
returning
  *

-- RoutineRepository.countEvents
select
  count(*) as "count"
from
  "assistant_routine_event"
where
  "assistant_routine_event"."routineId" = $1

-- RoutineRepository.createRun
insert into
  "assistant_routine_run" (
    "routineId",
    "ownerId",
    "trigger",
    "approvalMode",
    "limits"
  )
values
  ($1, $2, $3, $4, $5)
returning
  *

-- RoutineRepository.getRun
select
  *
from
  "assistant_routine_run"
where
  "assistant_routine_run"."id" = $1

-- RoutineRepository.getRuns
select
  "assistant_routine_run".*,
  (
    select
      count(*) as "count"
    from
      "assistant_routine_approval"
    where
      "assistant_routine_approval"."runId" = "assistant_routine_run"."id"
      and "assistant_routine_approval"."status" = $1
  ) as "pending"
from
  "assistant_routine_run"
where
  "assistant_routine_run"."routineId" = $2
order by
  "assistant_routine_run"."createdAt" desc
limit
  $3

-- RoutineRepository.getLatestRuns
select distinct
  on ("assistant_routine_run"."routineId") *
from
  "assistant_routine_run"
where
  "assistant_routine_run"."routineId" in ($1)
order by
  "assistant_routine_run"."routineId",
  "assistant_routine_run"."createdAt" desc

-- RoutineRepository.updateRun
update "assistant_routine_run"
set
  "status" = $1
where
  "assistant_routine_run"."id" = $2
returning
  *

-- RoutineRepository.claimRun
update "assistant_routine_run"
set
  "status" = $1,
  "tokenHash" = $2,
  "startedAt" = $3
where
  "assistant_routine_run"."id" = $4
  and "assistant_routine_run"."status" = $5
returning
  *

-- RoutineRepository.getRunByTokenHash
select
  *
from
  "assistant_routine_run"
where
  "assistant_routine_run"."tokenHash" = $1
  and "assistant_routine_run"."status" = $2

-- RoutineRepository.countToolCall
update "assistant_routine_run"
set
  "toolCalls" = "assistant_routine_run"."toolCalls" + $1
where
  "assistant_routine_run"."id" = $2
returning
  *

-- RoutineRepository.countChanges
update "assistant_routine_run"
set
  "changes" = "assistant_routine_run"."changes" + $1
where
  "assistant_routine_run"."id" = $2

-- RoutineRepository.countRoutineRuns
select
  count(*) as "count"
from
  "assistant_routine_run"
where
  "assistant_routine_run"."routineId" = $1
  and "assistant_routine_run"."createdAt" >= $2
  and "assistant_routine_run"."status" != $3

-- RoutineRepository.countOwnerRuns
select
  count(*) as "count"
from
  "assistant_routine_run"
where
  "assistant_routine_run"."ownerId" = $1
  and "assistant_routine_run"."createdAt" >= $2
  and "assistant_routine_run"."status" != $3

-- RoutineRepository.countRunning
select
  count(*) as "count"
from
  "assistant_routine_run"
where
  "assistant_routine_run"."status" = $1

-- RoutineRepository.failRunning
update "assistant_routine_run"
set
  "status" = $1,
  "error" = $2,
  "tokenHash" = $3,
  "finishedAt" = $4
where
  "assistant_routine_run"."status" = $5
returning
  "assistant_routine_run"."id",
  "assistant_routine_run"."routineId"

-- RoutineRepository.getRunAssetIds
select
  unnest("activity_log"."assetIds") as "assetId"
from
  "activity_log"
where
  "activity_log"."userId" = $1
  and "activity_log"."createdAt" >= $2
  and exists (
    select
      "assistant_routine_run"."id"
    from
      "assistant_routine_run"
    where
      "assistant_routine_run"."id" = "activity_log"."groupId"
  )

-- RoutineRepository.createApproval
insert into
  "assistant_routine_approval" (
    "runId",
    "ownerId",
    "toolName",
    "title",
    "summary",
    "input",
    "expiresAt"
  )
values
  ($1, $2, $3, $4, $5, $6, $7)
returning
  *

-- RoutineRepository.getApprovals
select
  *
from
  "assistant_routine_approval"
where
  "assistant_routine_approval"."runId" = $1
order by
  "assistant_routine_approval"."createdAt"

-- RoutineRepository.getApprovalsByIds
select
  *
from
  "assistant_routine_approval"
where
  "assistant_routine_approval"."ownerId" = $1
  and "assistant_routine_approval"."id" in ($2)
order by
  "assistant_routine_approval"."createdAt"

-- RoutineRepository.getPendingApprovals
select
  "assistant_routine_approval".*,
  "assistant_routine"."id" as "routineId",
  "assistant_routine"."name" as "routineName"
from
  "assistant_routine_approval"
  inner join "assistant_routine_run" on "assistant_routine_run"."id" = "assistant_routine_approval"."runId"
  inner join "assistant_routine" on "assistant_routine"."id" = "assistant_routine_run"."routineId"
where
  "assistant_routine_approval"."ownerId" = $1
  and "assistant_routine_approval"."status" = $2
order by
  "assistant_routine_approval"."createdAt"

-- RoutineRepository.countPendingApprovals
select
  count(*) as "count"
from
  "assistant_routine_approval"
where
  "assistant_routine_approval"."ownerId" = $1
  and "assistant_routine_approval"."status" = $2

-- RoutineRepository.claimApprovals
update "assistant_routine_approval"
set
  "status" = $1,
  "decidedAt" = $2
where
  "assistant_routine_approval"."ownerId" = $3
  and "assistant_routine_approval"."id" in ($4)
  and "assistant_routine_approval"."status" = $5
  and "assistant_routine_approval"."expiresAt" > $6
returning
  *

-- RoutineRepository.updateApproval
update "assistant_routine_approval"
set
  "status" = $1
where
  "assistant_routine_approval"."id" = $2
returning
  *

-- RoutineRepository.expireApprovals
update "assistant_routine_approval"
set
  "status" = $1,
  "decidedAt" = $2
where
  "assistant_routine_approval"."status" = $3
  and "assistant_routine_approval"."expiresAt" <= $4
returning
  "assistant_routine_approval"."id"
