-- NOTE: This file is auto generated by ./sql-generator

-- YearRecapRepository.getAssets
select
  "asset"."id",
  "asset"."type",
  "asset"."isFavorite",
  "asset"."localDateTime",
  "asset_exif"."latitude",
  "asset_exif"."longitude",
  "asset_exif"."city",
  "asset_exif"."state",
  "asset_exif"."country"
from
  "asset"
  left join "asset_exif" on "asset_exif"."assetId" = "asset"."id"
where
  "asset"."ownerId" = $1
  and "asset"."visibility" = 'timeline'
  and "asset"."deletedAt" is null
  and "asset"."type" in ($2, $3)
  and "asset"."localDateTime" >= $4
  and "asset"."localDateTime" < $5
  and (
    not exists (
      select
        1 as "one"
      from
        "asset_face"
      where
        "asset_face"."assetId" = "asset"."id"
        and "asset_face"."deletedAt" is null
        and (
          "asset_face"."personGroupId" = any ($6::uuid[])
          or exists (
            select
              1 as "one"
            from
              "face_identity_face"
              inner join "person" on "person"."identityId" = "face_identity_face"."identityId"
            where
              "face_identity_face"."assetFaceId" = "asset_face"."id"
              and "person"."personGroupId" = any ($7::uuid[])
          )
        )
    )
    and (
      "asset"."localDateTime" < $8
      or "asset"."localDateTime" >= $9
    )
    and not exists (
      select
        1 as "one"
      from
        "tag_asset"
        inner join "tag" on "tag"."id" = "tag_asset"."tagId"
      where
        "tag_asset"."assetId" = "asset"."id"
        and (
          "tag"."value" ilike $10
          or "tag"."value" ilike $11
          or "tag"."value" ilike $12
          or "tag"."value" like $13
          or "tag"."value" like $14
          or "tag"."value" like $15
          or "tag"."value" like $16
          or "tag"."value" like $17
          or "tag"."value" like $18
          or "tag"."value" like $19
          or "tag"."value" like $20
          or "tag"."value" like $21
          or "tag"."value" like $22
          or "tag"."value" like $23
          or "tag"."value" like $24
        )
    )
  )
  and exists (
    select
      "asset_file"."assetId"
    from
      "asset_file"
    where
      "asset_file"."assetId" = "asset"."id"
      and "asset_file"."type" = $25
  )
order by
  "asset"."localDateTime" asc,
  "asset"."id" asc

-- YearRecapRepository.getPeople
select
  "person"."personGroupId" as "id",
  "person"."name",
  "person"."type",
  count(distinct "asset"."id")::int as "count"
from
  "asset"
  inner join "asset_face" on "asset_face"."assetId" = "asset"."id"
  inner join "person" on "person"."personGroupId" = "asset_face"."personGroupId"
  and "person"."ownerId" = "asset"."ownerId"
where
  "asset"."ownerId" = $1
  and "asset"."visibility" = 'timeline'
  and "asset"."deletedAt" is null
  and "asset"."type" in ($2, $3)
  and "asset"."localDateTime" >= $4
  and "asset"."localDateTime" < $5
  and (
    not exists (
      select
        1 as "one"
      from
        "asset_face"
      where
        "asset_face"."assetId" = "asset"."id"
        and "asset_face"."deletedAt" is null
        and (
          "asset_face"."personGroupId" = any ($6::uuid[])
          or exists (
            select
              1 as "one"
            from
              "face_identity_face"
              inner join "person" on "person"."identityId" = "face_identity_face"."identityId"
            where
              "face_identity_face"."assetFaceId" = "asset_face"."id"
              and "person"."personGroupId" = any ($7::uuid[])
          )
        )
    )
    and (
      "asset"."localDateTime" < $8
      or "asset"."localDateTime" >= $9
    )
    and not exists (
      select
        1 as "one"
      from
        "tag_asset"
        inner join "tag" on "tag"."id" = "tag_asset"."tagId"
      where
        "tag_asset"."assetId" = "asset"."id"
        and (
          "tag"."value" ilike $10
          or "tag"."value" ilike $11
          or "tag"."value" ilike $12
          or "tag"."value" like $13
          or "tag"."value" like $14
          or "tag"."value" like $15
          or "tag"."value" like $16
          or "tag"."value" like $17
          or "tag"."value" like $18
          or "tag"."value" like $19
          or "tag"."value" like $20
          or "tag"."value" like $21
          or "tag"."value" like $22
          or "tag"."value" like $23
          or "tag"."value" like $24
        )
    )
  )
  and "asset_face"."deletedAt" is null
  and "person"."isHidden" = $25
  and "person"."name" != $26
group by
  "person"."personGroupId",
  "person"."name",
  "person"."type"
order by
  "count" desc,
  "person"."name" asc

-- YearRecapRepository.getJournalTags
select
  "asset"."id",
  "tag"."value"
from
  "asset"
  inner join "tag_asset" on "tag_asset"."assetId" = "asset"."id"
  inner join "tag" on "tag"."id" = "tag_asset"."tagId"
where
  "asset"."ownerId" = $1
  and "asset"."visibility" = 'timeline'
  and "asset"."deletedAt" is null
  and "asset"."type" in ($2, $3)
  and "asset"."localDateTime" >= $4
  and "asset"."localDateTime" < $5
  and (
    not exists (
      select
        1 as "one"
      from
        "asset_face"
      where
        "asset_face"."assetId" = "asset"."id"
        and "asset_face"."deletedAt" is null
        and (
          "asset_face"."personGroupId" = any ($6::uuid[])
          or exists (
            select
              1 as "one"
            from
              "face_identity_face"
              inner join "person" on "person"."identityId" = "face_identity_face"."identityId"
            where
              "face_identity_face"."assetFaceId" = "asset_face"."id"
              and "person"."personGroupId" = any ($7::uuid[])
          )
        )
    )
    and (
      "asset"."localDateTime" < $8
      or "asset"."localDateTime" >= $9
    )
    and not exists (
      select
        1 as "one"
      from
        "tag_asset"
        inner join "tag" on "tag"."id" = "tag_asset"."tagId"
      where
        "tag_asset"."assetId" = "asset"."id"
        and (
          "tag"."value" ilike $10
          or "tag"."value" ilike $11
          or "tag"."value" ilike $12
          or "tag"."value" like $13
          or "tag"."value" like $14
          or "tag"."value" like $15
          or "tag"."value" like $16
          or "tag"."value" like $17
          or "tag"."value" like $18
          or "tag"."value" like $19
          or "tag"."value" like $20
          or "tag"."value" like $21
          or "tag"."value" like $22
          or "tag"."value" like $23
          or "tag"."value" like $24
        )
    )
  )
  and "tag"."userId" = $25
  and (
    "tag"."value" like $26
    or "tag"."value" like $27
    or "tag"."value" like $28
    or "tag"."value" like $29
    or "tag"."value" like $30
    or "tag"."value" like $31
    or "tag"."value" like $32
    or "tag"."value" like $33
    or "tag"."value" like $34
    or "tag"."value" like $35
  )
order by
  "asset"."localDateTime" asc
